- src/commands/tileset-validate/tileset.validate.ts
Small change to log error if tileset validation fails, so that it is obvious in the Argo Workflow for TDE-586.
> fix: error if tileset validation fails TDE-586

- src/commands/copy/copy-worker.ts
- src/utils/concurrent.queue.ts
should fix us seeing stack traces without context
```
node:internal/event_target:1006
process.nextTick(() => { throw err; });
^
Error: Cannot overwrite file: s3://linz-workflow-artifacts/2022-12/15-imagery-standardising-v0.2.0-60-l8jb8/flat/BC35_5000_0206.tiff source:s3://linz
-workflow-artifacts/2022-12/15-imagery-standardising-v0.2.0-60-l8jb8/imagery-standardising-v0.2.0-60-l8jb8-standardise-validate-4104332785/tmp/BC35_5
000_0206.tiff
at file:///app/commands/copy/copy-worker.js:32:31
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Worker instance at:
at [kOnErrorMessage] (node:internal/worker:290:10)
at [kOnMessage] (node:internal/worker:301:37)
at MessagePort.<anonymous> (node:internal/worker:202:57)
at …
```
> fix: concurrenct queue should not stack trace on error

- package.json
- src/commands/create-manifest/__test__/create-manifest.test.ts
- src/commands/create-manifest/create-manifest.ts
- src/utils/chunk.ts
- yarn.lock
In order to be able to not flatten by default the the target path when creating a manifest, a new argument `--flatten` had been added to the `create-manifest` command.
> feat!: create-manifest allows flatten as optional

- .github/dependabot.yml
dependency upgrades were coming through as "feat" showing up in the change log.
> ci: dep upgrades are not features

- .github/workflows/push.yml
When publishing release, the action on any merge on master is still run too so you've got in this example a tag v0.5.x-gx which is the "same" version than the tag v0.6.x
> ci: avoid tagging container with push.yml when publishing release TDE-610

- package.json
- src/commands/copy/copy-worker.ts
- src/commands/create-manifest/__test__/create-manifest.test.ts
- src/direct/copy.ts
- src/fs.register.ts
- src/utils/__test__/argo.test.ts
- yarn.lock
The latest NodeJS lambdas in AWS are now on aws-sdk-v3 which has made me  want  to start migrating things to it.
I am using argo-tasks as a test bed for some v3 changes before updating basemaps.
> feat: move to aws-sdk-v3

- README.md
- src/commands/lds-cache/lds.cache.ts
--target was expecting a file, but with multiple downloads it has to be a directory
> fix: allow multiple downloads from LDS cache

- .github/workflows/push.yml
- .github/workflows/release-please.yml
Use --all-tags flag in order to avoid falling into a rate limit by pushing multiple tags in sequence
Same change for `topo-imagery` https://github.com/linz/topo-imagery/pull/315
> ci: use docker push --all-tags to avoid multiple push TDE-626

- src/commands/copy/copy-worker.ts
When throwning in a child worker the composite error's "reason" gets lost, and makes it hard to know why the error was thrown.
> feat(copy): log errors in child workers as composite error reasons get swallowed TDE-637

- Dockerfile
We have having intermittent DNS failures with "getaddrinfo EAI_AGAIN"
> fix: stop using alpine images

- .github/dependabot.yml
they happen far to often and create too much noise.
> build: ignore aws sdk patch updates

- src/commands/stac-validate/__test__/stac.validate.test.ts
- src/commands/stac-validate/stac.validate.ts
Calling `stac-validate --recursive` would fail using a local path:
```
{"level":30,"time":1681767643384,"pid":1,"hostname":"7efca33c9249","id":"01GY8JKDVG22VPN5JQK0XFGKY5","msg":"StacValidation:Start"}
{"level":30,"time":1[6](https://github.com/paulfouquet/argo-tasks-test/actions/runs/4726094077/jobs/8385289001#step:4:7)81[7](https://github.com/paulfouquet/argo-tasks-test/actions/runs/4726094077/jobs/8385289001#step:4:8)67643700,"pid":1,"hostname":"7efca33c9249","id":"01GY8JKDVG22VPN5JQK0XFGKY5","type":"Catalog","path":"data/stac/catalog.json","msg":"Validation:Done:Ok"}
{"level":50,"time":16[8](https://github.com/paulfouquet/argo-tasks-test/actions/runs/4726094077/jobs/8385289001#step:4:9)1767643700,"pid":1,"hostname":"7efca33c[9](https://github.com/paulfouquet/argo-tasks-test/actions/run …
```
> fix: stac-validate --recursive fails with local path TDE-732

- .github/workflows/push.yml
- .github/workflows/release-please.yml
- Dockerfile
- src/cli.info.ts
- src/commands/common.ts
- src/commands/copy/copy-worker.ts
- src/commands/copy/copy.ts
- src/commands/create-manifest/create-manifest.ts
- src/commands/group/group.ts
- src/commands/index.ts
- src/commands/lds-cache/lds.cache.ts
- src/commands/list/list.ts
- src/commands/stac-catalog/stac.catalog.ts
- src/commands/stac-github-import/stac.github.import.ts
- src/commands/stac-sync/stac.sync.ts
- src/commands/stac-validate/stac.validate.ts
- src/commands/tileindex-validate/tileindex.validate.ts
- src/direct/copy.ts
- src/log.ts
Switching to the docker container lables gives us a bunch of extra information in all of our containers
from `docker inspect ghcr.io/linz/argo-tasks:v2.10.0-14-gec6bfb1`
```json
"Env": [
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"NODE_VERSION=18.16.1",
"YARN_VERSION=1.22.19",
"GIT_VERSION=v2.10.0-14-gec6bfb1",
"GIT_HASH=ec6bfb17e8527856e56b79e00def33ffff6f2907",
"NODE_ENV=production"
],
"Labels": {
"org.opencontainers.image.created": "2023-07-12T00:14:32.434Z",
"org.opencontainers.image.description": "Utility tasks for working with Argo + LINZs AWS accounts",
"org.opencontainers.image.licenses": "NOASSERTION",
"org.opencontainers.image.revision": "ec6bfb17e8527856e56b79e00def33ffff6f2907",
"org.opencontainers.image.source": "https://github.com/linz/argo-tasks", …
```
> feat: include git version info in container

- src/cli.info.ts
- src/commands/group/group.ts
When artifact errors occur in argo its hard to figure out exactly what files were written and what is in those files. 
This increases the logging to explain exactly which files were written and some information about their contents.
When running argo containers having the exact github action that made the container is very useful, we were loosing the -attempt number so it was not possible to get the exact version number.
> feat(group): increase logging for grouping

- .github/dependabot.yml
Dependabot tries to update deps one at a time, often this leads to issues where dep updates are somewhat interrelated :eyes: `@aws-sdk/*` which leads to situations where you may have multiple aws-sdk pull requests but none can be merged individually.
This adds the beta grouping feature for `aws-sdk` and `chunkd` as a test to see how well this works.
> build: group similar deps into a single build

- README.md
- src/commands/basemaps-github/create-pr.ts
This will enable the new cogify workflow to input the targets for creation pull request.
The new cogify will output an array of target s3 location for each imported imagery. We need to parse the layer information for these targets and prepare pull request.
> feat(basemaps): Update the create-pr cli to take targets as input.

- .github/dependabot.yml
Basemaps `@basemaps/*` upgrades are often related so group them into a single dependabot pull request.
> build: group basemaps dep upgrade

- src/commands/basemaps-github/create-pr.ts
- src/commands/basemaps-github/make.cog.github.ts
Import the types from files directly to stop import dynamo into the bundle file. 
aws-sdk are required when using `@basemaps/shared` package. As this is not required, we should not import the whole package into code.
*If not applicable, provide explanation of why.*
> fix(basemaps): Import config types from the file to avoid importing dynamo

- src/commands/format/pretty.print.ts
- src/commands/stac-github-import/stac.github.import.ts
`formatFile()` does not wait for the file to be written.
Fix https://github.com/linz/imagery/actions/runs/6295092499/job/17087888283
> fix: collection.json is pushed to gh before pretty-printed TDE-893

- .github/workflows/push.yml
- .github/workflows/release-please.yml
**motivation**
New ecr repositories have been created (https://github.com/linz/topo-aws-infrastructure/pull/206) and we need to deploy our containers to these new locations
**modification**
changed actions to push containers to new repositories.
For example: argo-tasks/latest rather than eks/argo-tasks-latest
> feat: re-point ci to argo-tasks ecr repository

- .github/workflows/push.yml
- .github/workflows/release-please.yml
We use a lot of ARM spot instances, which causes both ARM and x86 nodes to be used when argo-tasks is used. So by publishing a ARM container of argo-tasks we can use the existing ARM spot instances
Adds `arm64` as a docker build platform
> build: publish arm containers

- README.md
- src/commands/index.ts
- src/commands/lint/__test__/lint.test.ts
- src/commands/lint/lint.constants.ts
- src/commands/lint/lint.s3.paths.ts
in order to be sure that workflow input public taraget paths follow conventions by linting workflow inputs where possible.
Adding lint-paths step to argo-tasks which will be used in `pubish-odr` and can also be added to `publish-copy`
Currently just the publish paths are linted (linz-imagery & nz-imagery) - this was based on the ticket description but more can be added if required. 
The dataset section of the s3 path is currently not linted as this is too variable to check?
(this change will be used in a topo-workflow PR currently WIP)
> feat: lint imagery input target paths TDE-857

- src/commands/basemaps-mapsheet/create-mapsheet.ts
We using the `--config` for the aws role config as default arguments in [argo tasks](https://github.com/linz/argo-tasks/blob/a56088232b91e4514e384f714656ea41dbefe695/src/fs.register.ts#L21). This is conflicts with the basemaps config argument. 
Rename the basemaps config argument to `bm-config`
> fix(basemaps): create-mapsheet config arg conflicts with role config arg

- src/commands/lint/__test__/lint.test.ts
- src/commands/lint/lint.s3.paths.ts
ensure that the resolution of the dataset name in the target key doesn't have a trailing 0.
For example:
0.3m not 0.30m 
(This is just for naming conventions and is written manually).
resolution check added to `lint-inputs` command
> feat: lint resolution TDE-938

- .github/workflows/push.yml
- .github/workflows/release-please.yml
Github deployment environments let us view what has been deployed where and is very helpful!
Add a `nonprod` and `prod` enviroment
Split the nonprod deployment to only on pushes to master
> ci: add nonprod and prod environments BM-923

- README.md
- src/commands/basemaps-github/make.cog.github.ts
- src/commands/stac-github-import/stac.github.import.ts
- src/utils/github.ts
To be consistent with Basemaps and so bulk processing for imagery and elevation is more reliable.
Move imagery and elevation GitHub Pull Requests from secrets to a PAT. Use existing Basemaps code, moving the core function into `utils` for common use.
Tests still run successfully.
> fix: GitHub PAT for Argo Workflows Pull Requests TDE-940

- src/commands/basemaps-github/make.cog.github.ts
- src/commands/stac-github-import/stac.github.import.ts
- src/utils/github.ts
Pass through an email address associated with the repository that the PR is for.
Set the Git commit author email depending on whether the repo is for `basemaps-config`, `elevation`, or `imagery`.
> fix: specify bot email address in Pull Requests TDE-983

- src/utils/__test__/slugify.test.ts
- src/utils/slugify.ts
- tsconfig.json
Allow us to easily slugify arbitrary strings for use in URLs.
This assumes that each part of a path will be slugified separately. This is less convenient than slugifying the entire path in one go, but ensures that no path segment contains a slash.
> feat: Slugify strings TDE-1019

- src/commands/path/path.generate.ts
This change provides the user with more information if an error were to occur.
`tiff.source.url` added to errror messages.
Resolves a nit in this [PR](https://github.com/linz/argo-tasks/pull/828)
~~- [ ] Tests updated~~ - n/a
~~- [ ] Docs updated~~ - n/a
> fix: add tiff url to error messages TDE-961

- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
- src/commands/tileindex-validate/tileindex.validate.ts
- src/utils/__test__/geotiff.test.ts
- src/utils/mapsheet.ts
Simplify TDE-1010 implementation
Rename parameters for clarity, use custom type for grid size, and make sure to wait for promise rejection.
>  refactor: Use custom type for grid size  TDE-1030

- src/commands/path/__test__/generate.path.test.ts
- src/commands/path/path.generate.ts
The target path name formatting is inconsistent with the final decisions in the naming.md
It is now expected that the event name will be included in the `geographic_description` field as well. 
Sometimes the event name includes the location (`Top of the South Floods`) and sometimes it does not (`Cyclone Gabrielle`) Therefore it is difficult to determine whether to merge the `event_name` with the `region`/`geographic_description`. 
It is also preferable to keep the `event_name` consistent across all imagery so that datasets can be filtered by events for example the Cyclone Gabrielle imagery in Hawkes Bay, Gisborne & the North Island should all have `event_name=Cyclone Gabrielle`.
inputs: `region=Hawke's Bay` `gd= Hawke's Bay Cyclone Gabrielle` `event_name=Cyclone Gabrielle`
paths: …
> fix: update target path naming hierarchy TDE-955

- src/commands/tileindex-validate/tileindex.validate.ts
Allow processing of the bottom row of map sheet tiles, pending refactoring and more robust mapsheet validation. This code will be removed when the mapsheet validation is updated.
There was a miscalculation that caused the lowest mapsheet row to be invalidated.
> fix: interim fix for Rakiura Stewart Island tiles TDE-1015

- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
- src/commands/tileindex-validate/tileindex.validate.ts
- src/utils/__test__/mapsheet.test.ts
- src/utils/mapsheet.ts
In addition to accepting the 50k grid size, this also produces tile names which consist of only the sheet code for 50k imagery. To do this efficiently the code irrelevant to this simpler code path have been rearranged to avoid unnecessary computation.
> feat: Handle 1:50k imagery TDE-1014

- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
to ensure we are correctly making tile names validate every known mapsheet
Improve test coverage for `getTileName`
> test: validate getTileName for all known mapsheets

- .github/workflows/release-please.yml
release-please.yml workflow should not try to login into AWS if AWS_CI_ROLE secret is not configured.
add a condition to login in AWS only if AWS_CI_ROLE exists
> ci: avoid login to AWS if AWS_CI_ROLE not configured

- src/commands/common.ts
- src/fs.register.ts
This reverts commit 18576e6a246c46dd65f26dc2a24c5531af9703d6 which caused issues when copying files due to `registerCli` being invoked in multiple places.
> revert: "refactor: Move default value up the stack TDE-1030 (#854)"

- src/commands/tileindex-validate/tileindex.validate.ts
In order to have a better overview of the errors, errors should be collected and logged at the end rathen than thrown ASAP.
- Avoid throwing error as soon as they're detected
- Couple of refactors to simplify the code
> fix: tileindex-validate errors should not been thrown asap TDE-1013

- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
- src/commands/tileindex-validate/tileindex.validate.ts
When all the TIFF locations are not extracted, the system should throw an error rather than only logging the errors.
Validate that all TIFF locations have been extracted before continuing the process.
> fix: validate that all TIFF locations have been extracted TDE-1013

- src/commands/tileindex-validate/tileindex.validate.ts
A regression that avoid validating all Tiff alignments has been introduced in https://github.com/linz/argo-tasks/pull/877 where the validateTiffAlignment() could not be called if `allValid` is false (due to short-circuited evaluation).
Store the result of each validation in a variable to make sure the function is called each time.
> fix: all tiff alignment should be validated TDE-1013

- src/commands/path/__test__/generate.path.test.ts
Actually check the error type.
Pass the error type into `assert.throws`.
> fix: Run `throws` with the right arguments TDE-1030

- src/commands/basemaps-github/create-pr.ts
- src/commands/basemaps-github/make.cog.github.ts
The `Event` category are populated as `New Aerial Photos` when creating pull request.
- the `parseCategory` not parsing the `event` and `scanned` category. Just added them to fix.
> fix(basemaps): Fix the event category is not parsed and populated in the pull request. BM-982

- src/commands/basemaps-github/make.cog.github.ts
- src/commands/stac-github-import/stac.github.import.ts
- src/utils/github.ts
This makes mocking the functionality much easier; see <https://github.com/nodejs/help/issues/4298>.
> refactor: Move `createPR` implementation to GitHub API method TDE-1100

- src/__test__/fqdn.test.ts
- src/fs.register.ts
Inside kubernetes dns resolution uses `ndots: 5` this means any dns requests that has less than 5 dots will go through all the search domains before looking up the actual domain. AWS s3 has 4 dots.
We are seeing 10-20 DNS requests per s3 DNS request due to the number of search domains as well as IPV6 requests.
Any DNS requests to S3 are modified to have a trailing "." to force the DNS lookup to be fully qualified.
> feat: force fully qualified domains for s3 requests TDE-1084

- package-lock.json
- package.json
- src/commands/basemaps-github/create-pr.ts
- src/commands/basemaps-github/make.cog.github.ts
- src/commands/stac-github-import/stac.github.import.ts
- src/utils/github.ts
We need to run another cron workflow to generate individual vector map output for the nz road addressing layer. So we need to allow the create-pr command to be able to add create pull request for it.
- Remove the hard coded topographic vector tileset logic
- Update the vector to parse the info from vector target and prepare new tileset for it.
- Update `getContent` to return null for Not Found
> feat(basemaps): Update the create-pr cli to add new individual vector tileset. BM-992

- src/__test__/eai_againRetry.test.ts
- src/fs.register.ts
Retry workflows that fail due to EAI_AGAIN errors. 
Added an SDK middleware to try 3 times when receiving an `EAI_AGAIN` error. 
> feat: EAI_AGAIN middleware TDE-1114

- src/commands/path/__test__/generate.path.test.ts
- src/commands/path/path.generate.ts
The original code used the original UTC datetimes in the STAC collection to work out the start and end years. But we want to use the local start and end years.
Localise datetime string before extracting the year.
> fix: Use Pacific/Auckland time zone for collection years TDE-1066

- src/utils/github.ts
Some of `create-pr` using the same branch names like the vector map etl, this might be cause the failure when a pull request exist for the branch. We should just skip the last step for creating pull when existing branch have a pull request opened. Because, the previous steps in create-pr commends already commit and updated the existing branch and PR. We can just skip pull request creation instead of failing. 
Example of [failure](https://argo.linzaccess.com/workflows/argo/cron-vector-etl-topographic-1713290400?tab=workflow&nodeId=cron-vector-etl-topographic-1713290400-2880775147&nodePanelView=summary&sidePanel=logs:cron-vector-etl-topographic-1713290400-2880775147:main&uid=99d03ed9-5aa8-49c5-95ba-236d21c40aba). 
- Add a catch at pull request creation API, to check the validation failure …
> feat(basemaps): Should skip creating pull request when exist instead of throwing errors. BM-1018

- src/commands/common.ts
- src/commands/tileindex-validate/tileindex.validate.ts
Only webp presets require tiffs to be 8bit 3 or 4 band tiffs, when processing dems or LZW we do not need to validate against 8bit
Validate tiffs against a 8bit only when the preset is webp.
> fix: only validate the tiffs are 8 bit if the preset is webp TDE-1151 TDE-895

- README.md
- src/commands/common.ts
- src/commands/stac-catalog/stac.catalog.ts
- src/commands/stac-sync/__test__/stac.sync.test.ts
- src/commands/stac-sync/stac.sync.ts
- src/commands/stac-validate/__test__/stac.validate.test.ts
- src/commands/stac-validate/hash.worker.ts
- src/commands/stac-validate/stac.validate.ts
- src/utils/__test__/hash.test.ts
- src/utils/hash.ts
We need a way to validate all the STAC files quickly. Validating the `assets` takes a long time but validating just the JSON files (`links`) should be fast.
- Add the ability to the `stac validate` command to validate the link checksums
- Allow the `stac validate` command to validate only the `link` checksums (using `--checksum-links`) or both `asset` and `links` (`--checksum`)
> feat: stac validate links checksum TDE-1134

- README.md
- src/commands/stac-validate/stac.validate.ts
Current `--checksum` and `--checksum-links` flags overlap in the following case
`--checksum --checksum-links`, where `--checksum`  will validate both asset and link checksums so `--checksum-links` becomes pointless and confusing in that case.
Allow to validate the asset checksums only.
- To validate both asset and links checksums: `--checksum-assets --checksum-links`
- To validate asset checksums only: `--checksum-assets`
- To validate link checksums only: `--checksum-links`
> feat!: allow to validate asset checksums only TDE-1134

- src/utils/__test__/chunk.test.ts
- src/utils/chunk.ts
Argo does not easily allow users to add multiple paths to their workflows so users want to 
have a single "path" that is a "\n" or ";" separated
Splits all paths on ";" or "\n" 
> feat: allow paths to be split on ";" or "\n"

- src/commands/basemaps-github/create-pr.ts
[Argo Error log](https://argo.linzaccess.com/workflows/argo/cron-vector-etl-topographic-1715709600?tab=workflow&nodeId=cron-vector-etl-topographic-1715709600-1555051635&nodePanelView=containers&sidePanel=logs:cron-vector-etl-topographic-1715709600-1555051635:&uid=bbdff6e5-809d-4970-a41a-c0a5bd954423)
Vector target is different from raster with have the filename at the end. like `s3://linz-basemaps/vector/3857/topographic/01HXW47WJAM1KMZVN4QXR7SA70/topographic.tar.co` instead of `s3://linz-basemaps/vector/3857/topographic/01HXW47WJAM1KMZVN4QXR7SA70/`
So we need to replace the filename to `collection.json` instead of just adding it to the target.
- get the filename from the url and validate it as cotar file extension.
- prepare the correct collection.json path.
> fix(basemaps): Fix the collection.json path for the vector data.

- src/commands/stac-sync/stac.sync.ts
When files are [uploaded to s3 via topo-imagery](https://github.com/linz/topo-imagery/blob/f95d39225e624c8375ad3e9b68d47409f8191a1a/scripts/files/fs_s3.py#L41), their checksum is stored in a s3 metadata key named `-multihash`. In order to keep consistency across our data, we would like to use the same key name everywhere.
Change the S3 metadata key name that store the checksum, when synchronizing the STAC, from `linz-hash` to `multihash`.
> fix: uniform checksum s3 metadata key TDE-1181

- src/commands/tileindex-validate/tileindex.validate.ts
- src/index.ts
The nodejs event loop is becoming empty due to a deadlock.
The deadlock occurs when the validate8BitTiff attempts to fetch more data from the tiff, the request to fetch the data is added to the TiffQueue, but since `validate8BitTiff` is already inside the `TiffQueue` the fetch can never run which causes the deadlock
Remove the tiff queue from validate8BitTiff as its already inside of the queue.
Add more logs to make it easier to understand if the process exited correctly.
TODO:
Is there a way to detect the deadlock and exit(1)? 
> fix: prevent deadlock when validating bits per sample TDE-1201

- src/commands/basemaps-github/make.cog.github.ts
The aerial config path is incorrect by using the filename.json, we should hard coded as aerial.json like others topographic.json and elevation.json
Fix the aerial config path to aerial.json
> fix(basemaps): Fix the aerial config path for create pr cli.

- .eslintrc.cjs
- package-lock.json
- package.json
- src/commands/basemaps-github/create-pr.ts
- src/commands/basemaps-github/make.cog.github.ts
- src/commands/basemaps-mapsheet/create-mapsheet.ts
- src/commands/common.ts
- src/commands/copy/copy-worker.ts
- src/commands/copy/copy.ts
- src/commands/create-manifest/create-manifest.ts
- src/commands/group/group.ts
- src/commands/path/__test__/generate.path.test.ts
- src/commands/path/path.generate.ts
- src/commands/stac-github-import/stac.github.import.ts
- src/commands/stac-sync/stac.sync.ts
- src/commands/stac-validate/__test__/stac.validate.test.ts
- src/commands/stac-validate/stac.validate.ts
- src/commands/tileindex-validate/__test__/tileindex.validate.data.ts
- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
- src/commands/tileindex-validate/tileindex.validate.ts
- src/index.ts
- src/utils/__test__/filter.test.ts
- src/utils/__test__/geotiff.test.ts
- src/utils/__test__/hash.test.ts
- src/utils/action.storage.ts
- src/utils/geotiff.ts
- src/utils/github.ts
- src/utils/hash.ts
Typescript v5.5 was recently released with many improvements, it would be good to keep upto date with the improved type checking
upgrades to typescript 5.5 and fixes a number of lint rules
Most fixes revolve around `any` and `async` improvements
- casting `.catch(e)` to `unknown` as e is `any`
- casting `JSON.parse` as its return is unknown
Async:
- functions that are async but do not contain a `await`
- promises that are triggered but do not have a `await` or `.catch()`
> build: upgrade to typescript 5.5

- src/commands/basemaps-github/make.cog.github.ts
When replacing existing layer with the same layer.name, we shouldn't overwrite the whole thing. We need to keep the existing settings like minZoom, maxZoom.
Add existing first and overwrite the duplicated values.
> fix(basemaps): Keep the existing settings when replacing existing layer.

- src/commands/tileindex-validate/__test__/tileindex.validate.data.ts
- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
- src/commands/tileindex-validate/tileindex.validate.ts
- src/utils/__test__/band.test.ts
- src/utils/band.ts
When tiffs are retiled they need to have consistent banding information or GDAL will not be able to join them together easily
When a retile is requested validate that all tiffs in the retile have the same consistent band information.
> fix: validate band information is consistent

- .gitignore
- Dockerfile
- src/commands/stac-validate/stac.validate.ts
_What does this change aim to achieve?_
We are seeing quite a few network related failures when validating JSON schema objects
Cache JSON schema objects locally when the docker container is built
_Why is this change being made? What implications or other considerations are there?_
> fix(stac-validate): cache json schema objects to reduce network failures TDE-1212

- package-lock.json
- package.json
- src/commands/stac-validate/stac.validate.ts
When validating large amounts of STAC documents concurrently sometimes `ajv.getSchema(url)` can cause a race condition which triggers the shcema to inccorectly load
Limit AJV's `compileAsync` to one compilation at a time.
Running 100 concurrent validations before the change fails most of the time
```typescript
for (let i = 0; i < 100; i++) {
queue.push(() => validateStac('/home/blacha/Downloads/collection_main.json'));
}
await queue.join();
```
> fix(stac-validate): work around race condition  when validating 100s of documents TDE-1212

- .github/workflows/push.yml
- .github/workflows/release-please.yml
deploy-nonprod-container job should only run on master merges which are not releases as release-please handles the container builds for everything else
fixes a bad commit message name so it should be ignored.
also re-adds whitespace between steps so its easier to follow
> build: only deploy nonprod containers on non release builds

- .github/workflows/pull-request-container.yml
It is useful to be able to test pull requests inside argo using a built container
Users can add "container" label to the pull request to have a pull request for the container to be built
> build: allow adding label "container" to create containers from pull requests

- src/commands/stac-github-import/stac.github.import.ts
Supply the `flatten` parameter to GitHub for the imagery and elevation repos; it is required for the `copy` workflow.
Add a fixed value of `false` for `flatten` to the parameters file added to GitHub.
> fix: include flatten parameter in stac-github-import TDE-1242

- src/commands/stac-github-import/stac.github.import.ts
Capture correct GitHub PR title and branch in the logs.
Use `title` and `branch` consts in the logs.
Build, formatting and test checks succeed.
> fix: correct GitHub PR title and branch logged

- src/commands/mapsheet-coverage/__test__/mapsheet.coverage.test.ts
- src/commands/mapsheet-coverage/mapsheet.coverage.ts
Fix a small typo that duplicated an output file.
Fixed output file name (and also fixed another, very minor, documentation typo).
> fix: mapsheet-coverage output filename typo TDE-1164

- src/__test__/fs.test.ts
- src/fs.register.ts
the middleware to retry EAI_AGAIN errors was not being added to new file systems when they are created, DNS errors on new file systems can still trigger failures.
register EAI_AGAIN middleware onto child file systems 
> fix: ensure EAI_AGAIN middleware is added to new file systems TDE-1268

- src/commands/copy/copy-worker.ts
- src/log.ts
when running in worker threads, some logs do not get the `id` and `threadId` added to them.
`const log = baseLogger.child({ id: args.id, threadId });` creates a entire new logger and a lot of places logs are logged from `baseLogger` not `log` so the `id` and `threadId` bindings are not added to those logs.
unfortunately `setBindings` only does addition of so extra keys, so duplicate keys cause problems eg `setBindings({ id: 1}); setBindings({ id : 2})` will trigger logs to be emitted as `{id: 1, id: 2}`
Child threads now have a `correlationId` of the parent process so they can be separated easily
All logs from the child thread should now have a `threadId`
> fix(copy): add threadId to all logs created when running from threads TDE-1268

- .github/workflows/push.yml
- package.json
I want a simplier command to generate the readme files. `npm run docs` after running `npm run build`
- add a `docs` script
> build: add script to generate readme files

- src/commands/basemaps-github/__test__/create-pr.test.ts
- src/commands/basemaps-github/create-pr.ts
Elevation s3 path is one more directory and the imagery s3 path. So the validate path need to get the espg and name with the correct index.
elevation: s3://linz-basemaps/elevation/3857/canterbury_2020-2023_dem_1m/01J868QZZ4RJ485PMWP1ECQYD0
imagery: s3://linz-basemaps/2193/gebco_2020_Nztm2000Quad_305-75m/01F1BFJN8R8P7BXN3XTHC5MT5G/
Get the espg and name from correct index for elevations.
> fix(basemaps): Get the epsg and name correctly for elevation s3 path. BM-1088

- src/commands/basemaps-github/create-pr.ts
We are now importing elevation data from `nz-elevation` bucket. So, it should be 
Add `nz-elevation` as valid source bucket.
> feat(basemaps): Add nz-elevation bucket as valid source s3 bucket. BM-1088

- .github/workflows/pull-request-container.yml
Most of our argo templates only allow tags to be changed a lot of them use our ECR based containers, so pull reuqest builds cannot be used inside of argo.
push to AWS ECR if the CI role exists.
> build: allow pushing pull request builds to aws ecr

- src/utils/__test__/mapsheet.test.ts
- src/utils/mapsheet.ts
Some tiles exist outside the "known" mapsheet range, it is helpful to generate names for these
add a method that can generate sheet codes outside the known range given a NZTM2000 X & Y.
> feat: expose method to calculate a sheet code from any x,y

- package-lock.json
- package.json
- src/commands/mapsheet-coverage/__test__/mapsheet.coverage.test.ts
- src/commands/mapsheet-coverage/mapsheet.coverage.ts
Quite a few of our datasets are aligned to a EPSG:2193 tile grid, when reprojecting these area polygons to a EPSG:4326, small slithers can appear 
for example in this dataset where one dataset (magenta) has 5 tiles across and one has 4 (blue) only the two corner points are stored
As you zoom in on the corner slithers appear
Find polygons that are very small and drop them.
> feat: attempt to remove slivers by dropping small polygons TDE-1130

- src/commands/basemaps-github/make.cog.github.ts
We don't need `"category": "Elevation",` for elevation combined config. We can delete if exists. The category is only for individual configs and aerial config.
Remove category for combined elevation configs layers
> fix(basemaps): Remove the elevation category for elevation layers. BM-1125

- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
- src/commands/tileindex-validate/tileindex.validate.ts
- src/utils/__test__/chunk.test.ts
- src/utils/chunk.ts
zero byte tiffs are currently just skipped when validating files
allow file readers to opt into listing zero byte files
> fix: include zero byte tiffs when validating files TDE-1348

- src/commands/common.ts
- src/commands/stac-setup/README.md
- src/commands/stac-setup/__test__/stac.setup.test.ts
- src/commands/stac-setup/stac.setup.ts
A change was made recently to accept the GSD in the format without a trailing `m` e.g. `0.3` rather than `0.3m`. However, the old format should still be accepted as this may accidentally be entered as a workflow parameter.
Small refactor to match refactor made to `generate-path` command when handling `GeospatialDataCategories`.
Add a function `formatGsd` to check the format of the GSD, remove a trailing `m` and log a warning.
> fix: remove GSD unit from stac setup command inputs TDE-1339 TDE-1211

- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
- src/commands/tileindex-validate/tileindex.validate.ts
As a user submitting datasets I want to poorly aligned source TIFF files to get aligned to our NZ 1:50k tile grid.
Updated `tileindex.validate.ts` to align input tiffs to our 1:50k tile grid.
> feat: retile datasets TDE-1352

- src/commands/stac-validate/stac.validate.ts
When a STAC validation fails on a link checksum, it requires some manual research to find which is the parent document that contains this failing link.
Add the following information in the checksum validation logs:
- Add the STAC document path of the parent that contains the link being checked
- Add the link rel or "type"
``` json
{"level":20,"time":1738618069598,"pid":129823,"hostname":"linz","id":"01JK6VCRF3BXTHK5HT9YZ11MZV","source":"memory://stac/item.json","checksum":"12206fd977db9b2afe87a9ceee48432881299a6aaf83d935fbbe83007660287f9c2e","type":"item","parent":"memory://stac/collection.json","duration":0.16163199999999733,"msg":"Checksum:Validation:Ok"}
```
> feat: improve stac-validate logs TDE-1385

- src/commands/generate-path/__test__/generate.path.test.ts
- src/commands/generate-path/path.generate.ts
- src/commands/stac-setup/stac.setup.ts
- src/utils/metadata.ts
To generate a national combined hillshade product, we need to be able generate correct output paths when processing the datasets.
- Added tests
- Added GeospatialDataCategories
- Added path template for newly created categories 
- Updated `slugFromMetadata` for basic support of hillshade datasets
Docs: no changes to usage of `generate-path` that require an update to the readme files.
> feat: generate paths for new national hillshade products TDE-1378

- src/commands/stac-setup/README.md
- src/commands/stac-setup/__test__/stac.setup.test.ts
- src/commands/stac-setup/stac.setup.ts
We are still receiving more historical imagery we need to ensure we can continue to process the historical imagery
Add survey id to the list of optional arguments for stac-setup so that slugs can include the historical survery eg
```
west-coast_otago_sn8321_1984-1985_0.375m
west-coast_sn8534_1985-1986_0.375m
west-coast_sn9641_1997_0.75m
```
Unit tests
> feat(stac-setup): support historical survey names LI-3977

- src/commands/stac-setup/README.md
- src/commands/stac-setup/__test__/stac.setup.test.ts
- src/commands/stac-setup/stac.setup.ts
With historical imagery processing we will need a way for being more specific with the dates as part of the setup, so to prepare for the upcoming historical imagery changes allow more specific dates to be supplied.
adds --start-date and --end-date that are mutually exclusive from their --start-year and --end-year that allow specifying the date as a `YYYY-MM-DD`
deprecate for --start-year and --end-year
Unit tests
> feat(stac-setup): support start dates

- src/commands/generate-path/__test__/generate.path.test.ts
- src/commands/generate-path/path.generate.ts
`generate-path` had a special naming rule for creating hillshade from 8m DEM. As we are now publishing all intermediate hillshades (1m, 8m) this special case has become the default.
The different path for the _merged_ hillshade (without _`gsd`m) is not able to be automatically generated as it stands, and can now be pulled from `odr_url`.
Remove special case for creating hillshade ODR paths.
> fix: harmonize hillshade odr paths TDE-1447

- src/commands/basemaps-github/create-pr.ts
- src/commands/basemaps-github/make.cog.github.ts
We are not importing elevation dsm layers into basemaps. We want the create-pr can automatically creating pull requests for the dsm import and update the layer into `elevations.dsm.json`
https://github.com/linz/basemaps-config/pull/1065 
- Check for `_dsm_` or `_dem_` from the `layer.name`, like `wellington_2013-2014_dsm_1m`.
- Add individual ones into `elevation/dem/wellington_2013-2014_dem_1m.json` or `elevation/dsm/wellington_2013-2014_dsm_1m.json`.
- Add combined into `elevation.json` for `dem` layer and `elevation.dsm.json` for `dsm` layer.
> feat(basemaps): Create pull request for the DSM import into elevation.dsm.json config. BM-1245

- src/commands/tileindex-validate/README.md
- src/commands/tileindex-validate/tileindex.validate.ts
The documentation was not specifying that the command can accept multiple source.
- Amend the description
> docs: improve tile-index-valitate documentation TDE-1403

- src/commands/generate-path/__test__/generate.path.test.ts
- src/commands/generate-path/path.generate.ts
- src/commands/stac-setup/stac.setup.ts
- src/utils/metadata.ts
As a Basemaps user
I want national DSM hillshades (1m and unspecified resolution, standard and igor)
So that I can view/accentuate terrain detail in a variety of basemaps.
Added appropriate constants to `metadata.ts`, `stac.setup.ts` and `path.generate.ts`.
DsmHillshade: 'dsm-hillshade',
DsmHillshadeIgor: 'dsm-hillshade-igor',
> feat: support national DSM hillshades TDE-1455

- src/commands/copy/copy.ts
- src/commands/identify-updated-items/__test__/identify.updated.items.test.ts
Copy workflow was broken since change to Node23
Updated copy worker to call `.ts` instead of `.js` and one other reference to a .js project file in tests.
> fix: update from .js to .ts files TDE-1474

- package.json
in Node 23.9 `node --test` would find all `**/*.test.ts` files and run them, this caused a number of issues for some repositories so node revered this change, in node 23.11 (current) `node --test` no longer finds `**/*.test.ts` to run, so none of the tests are running in this repository
force node to find `src/**/*.test.ts` and run them when using `node --test`
Ran locally on node 23.9 and 23.11.
> build: correct path for test runner

- src/commands/stac-github-import/README.md
- src/commands/stac-github-import/stac.github.import.ts
There is a new ODR bucket `s3://nz-coastal` that uses the https://github.com/linz/argo-tasks GitHub repository for provisioning datasets.
Add the `linz/coastal` repository and associated `linz-li-bot` GitHub account email address.
Remove out of date try/catch block that is no longer needed now that Basemaps support Elevation configs.
> feat: add linz/coastal repo TDE-1456

- .github/workflows/push.yml
The node version has been forgotten to be upgraded to use the `linz-action-typescript` causing npm test scripts [to fail](https://github.com/linz/argo-tasks/actions/runs/14697476826/job/41241186400).
- use node 23.x to call `linz-action-typescript`
> ci: use node v23 for linz-action-typescript

- .github/workflows/pull-request-container.yml
- .github/workflows/push.yml
- .github/workflows/release-please.yml
- Dockerfile
node23 was only used as it is added support for running typescript directly, this pr changes to a more stable release channel
swap to node24
CI/CD to verify build and deploy, ran container locally
> build: upgrade to node24 as it is the next lts

- src/commands/common.ts
- src/commands/identify-updated-items/identify.updated.items.ts
- src/commands/mapsheet-coverage/mapsheet.coverage.ts
- src/commands/tileindex-validate/__test__/tileindex.validate.test.ts
- src/commands/tileindex-validate/tileindex.validate.ts
- src/utils/__test__/filelist.test.ts
- src/utils/filelist.ts
Some input locations have very complex URLs, for example `s3://blacha-test/🦄 🌈/input.tiff`, when converting this location to a URL the path is URL encoded with `%`, when requesting URLs via the AWS SDK, the AWS SDK will automatically encode the URL again, causing a duplication of encoding. For example `%20` turns into `%2520` then S3 will fail to return the right object.
Add unit tests to validate our input and outputs to ensure URLS are not encoded for input and output
Add unit tests to validate commands can handle utf8 inputs 🦄🌈🦄🌈
ran unit tests + ran CLI locally
> fix: allow reading from complex 🦄🌈 URLs TDE-1504

- src/commands/stac-setup/README.md
- src/commands/stac-setup/stac.setup.ts
Geographic description is an optional metadata. 
- set `--geographic-description` as optional
Ran without passing `--geographic-description`
> fix: stac-setup `--geographic-description` should be optional TDE-1510

- src/commands/common.ts
- src/index.ts
If a command fails to start (for example, missing arguments), the package information (for example, `"package":{"package":"@linzjs/argo-tasks","version":"v4.14.2","hash":"e8dbf80c51b7a2baf61b22eec49de7072c812223","buildId":""}`) is not logged. Without this information, it makes it difficult to reproduce.
- Move package info logs before the command run
Local test
> fix: package information is not logged when command has not started TDE-1511

- src/commands/generate-path/__test__/generate.path.test.ts
- src/commands/generate-path/path.generate.ts
As the slug generation enable creating the slug for the scanned-aerial-photos, the path generation should too.
- Allow path generation for the scanned-aerial-photo category
automated tests
> feat: generate path for scanned-aerial-photos TDE-1522

- src/commands/basemaps-github/create-pr.ts
- src/commands/basemaps-github/make.cog.github.ts
For the topographic config file with the following format, and we will move to versions tag at the end of json filename.
[For example](https://github.com/linz/basemaps-config/blob/master/config/tileset/topographic-v2.json): 
`config/tileset/topographic-v2.json`
->
```
{
"type": "vector",
"id": "ts_topographic-v2",
"title": "New Zealand Topographic Vector Map",
"maxZoom": 15,
"format": "pbf",
"layers": [
{
"3857": "s3://linz-basemaps/vector/3857/topographic/01JP1H9Z44EX3TPRJD6GNZBV58/topographic-v2.tar.co",
"name": "topographic-v2",
"title": "Topographic V2"
}
]
}
```
So we need use the filename `topographic-v2.tar.co` to parse the name for pull request creation.
Get the vector layer name from filename instead of the path
Local tested.
> fix(basemaps): Fix the topographic pull request creation to support topgraphic-v2. BM-1203

- src/commands/basemaps-github/create-pr.ts
We are starting to create vector map in NZTM projection and we could remove the check for Webmecator only.
Remove the check for vector map epsg code in the url
Tested in argo. 
https://argo.linzaccess.com/workflows/argo/test-basemaps-vector-etl-shortbread-pvrdg?tab=workflow&nodeId=test-basemaps-vector-etl-shortbread-pvrdg-2737806755&uid=7425f2b1-d218-48e4-ba7a-d174b2ecbe42
> feat(basemaps): Add support for NZTM vector tiles in PR creation

- .github/workflows/pull-request-container.yml
- .github/workflows/push.yml
- .github/workflows/release-please.yml
- Dockerfile
- package-lock.json
- package.json
Our current github action builds are failing.
Updated package.json to the current node version used by github actions (24.5.0)
Updated package-lock.json
Pinned node versions in github actions to 24.5.0 (was 24.x)
builds succeed.
> chore: update node.js to 24.5 to match gh actions TDE-1600

- src/commands/verify-restore/__test__/verify.restore.test.ts
- src/commands/verify-restore/verify.restore.ts
S3 Batch Operations report results CSV encode the object keys. They need to be decoded before fetching the objects.
decode the URL
also fix a parsing issue
Automated tests
> fix: decode url passed from CSV report TDE-1603

- src/commands/verify-restore/__test__/verify.restore.test.ts
- src/commands/verify-restore/verify.restore.ts
`ResultMessage` can contain a carriage return character `\r`.
trim `ResultMessage`
Update doc related to AWS providing wrong CSV schema
manual tests
automated tests
> fix: `ResultMessage` should be trimmed TDE-1554

- src/commands/verify-restore/__test__/verify.restore.test.ts
- src/commands/verify-restore/verify.restore.ts
AWS returns additional information in the `Restore` field such as the expiry date but the system checks exact match for `ongoing-request=false`. This causes the restore check to return `false` even when the restore was actually completed.
- use `includes()` instead of strict equality
- minor refactor
Manual and automated tests
> fix: ongoing-request=false is not parsed correctly TDE-1554

- src/commands/delete-empty-folders/delete.empty.folders.ts
newly released `deleteEmptyFolders` did not work on local filesystems.
Additional checks in `isFolder` as well as a workaround for the `fsa.delete()` function, which used to fail when trying to delete folders on local FS.
Tests on local FS and unit tests.
> fix: local folders did not get deleted TDE-1627

- src/commands/mapsheet-coverage/mapsheet.coverage.ts
mapsheet-coverage incorrectly identifies all items as new.
Fix string comparison (remove "basename") and hash the correct file (STAC Item, not TIFF asset)
manual local test run 
`node src/index.ts mapsheet-coverage --verbose --location https://raw.githubusercontent.com/linz/basemaps-config/master/config/tileset/elevation.json --epsg-code 2193 --compare=s3://nz-elevation/new-zealand/new-zealand/dem_1m/2193/collection.json`
> fix: mapsheet coverage identifies all items as new TDE-1641

- src/commands/generate-path/__test__/generate.path.test.ts
- src/commands/generate-path/path.generate.ts
aerial-photos is a category available in our argo workflows, but the standardising workflow fails to create STAC when selected.
Add `GeospatialDataCategories.AerialPhotos` as a valid category in function `generatePath` and appropriate test.
Passing unit tests.
> fix: accept aerial-photos as category TDE-1650

- src/commands/copy/copy-worker.ts
As a Data Manager 
I want to increase the default zstd compression level for archive workflows
so that our long term archives are as small as possible
Set
`[constants.ZSTD_c_compressionLevel]: 17,`
when creating `ZstdCompress`
unit tests continue to pass and manually confirmed compression produces smaller files.
> feat: increase default zstd compression level TDE-1591
