linz/argo-tasks

package.json, src/commands/list/__test__/filter.test.ts, src/commands/list/list.ts, yarn.lock
--exclude takes priority if something is excluded it will no be included
this removes --filter in favor of --include/--exclude
=> feat!: add --exclude and --include for list

src/commands/copy/copy.ts, src/commands/flatten/flatten.ts
- feat: add copy and flatten commands to move source iamgery around
- feat: allow copy to be base64 gzip json
- feat: add concurrency flag
=> feat: allow compressed output

src/commands/stac-validate/stac.validate.ts
=> feat: validate stac_extensions TDE-503

src/commands/copy/copy.ts, src/commands/flatten/flatten.ts, src/utils/__test__/argo.test.ts, src/utils/argo.ts, src/utils/chunk.ts, src/utils/s3.action.ts
- feat(flatten): store the manifest of what is going to be flattened into s3 rather than argo
- fix: do not include empty files
=> feat(flatten): store the manifest of what is going to be flattened into s3 rather than argo

.github/workflows/push.yml, Dockerfile, package.json, yarn.lock
this allows us to run custom commands more easily inside this container
=> fix: add the entire source and stop bundling the CLI

src/commands/lds-cache/lds.cache.ts
This changes the interface from `--layerId :layerId --version :version` to `layerId@version layerId@version`
=> feat!: allow multiple layers to be downloaded with the layer downloader

.github/workflows/push.yml, .github/workflows/release-please.yml, src/commands/create-manifest/__test__/create-manifest.test.ts
=> feat: use action-typescript v2

.github/workflows/push.yml, .github/workflows/release-please.yml
https://github.com/aws-actions/amazon-ecr-login#examples-of-usage
https://github.com/linz/topo-imagery/pull/408
https://github.com/linz/topo-imagery/pull/415
=> ci: publish containers to ECR TDE-705

.github/workflows/push.yml
sorry, should have checked this after the same error on topo-imagery
=> fix: unescaped bracket

README.md, src/commands/index.ts, src/commands/stac-catalog/__test__/stac.catalog.test.ts, src/commands/stac-catalog/stac.catalog.ts
Create STAC catalog JSON file when given links to catalog template JSON file and collection links file (linebreak separated string).
=> feat: create stac-catalog TDE-724

package.json, src/commands/stac-validate/stac.validate.ts, src/log.ts, tsconfig.json, yarn.lock
also fixes a few typing issues that will cause issues once ESM modules are default in linzjs/style
=> build: upgrade chunkd

src/commands/index.ts, src/commands/stac-sync/__test__/stac.sync.test.ts, src/commands/stac-sync/stac.sync.ts
add a file hash to the object metadata on AWS S3 to determine if file has been modified
Has been tested here https://github.com/linz/imagery-test/actions/runs/4909985617/jobs/8766726824
=> feat: synchronize stac TDE-725

src/commands/tileset-validate/tileset.validate.ts, src/utils/__test__/mapsheet.test.ts, src/utils/mapsheet.ts
This greatly increases the docmentation for all of the topographic 1:50k tile index api operations
=> feat: organised the mapsheet api

Dockerfile
This reverts commit 7b8729a302914536f8d5edac93169482ec49c3da.
=> Revert "fix: move away from docker.io containers TDE-684 (#477)"

README.md
Would be good to generate this from the in-code documentation in future.
=> docs: update README with newer commands TDE-766

src/utils/__test__/mapsheet.test.ts, src/utils/mapsheet.ts
height should be negative in NZTM.
=> fix: do not mix image width and height with projection x and y.

src/commands/basemaps-github/create-pr.ts, src/commands/basemaps-github/make.cog.github.ts
- We should validate the bucket from target and source location, before creating pull request in basemaps-config repo.
- If this is an individual layer, we will try to get the region from the source url.
- Add a check to make sure the target bucket is `linz-basemaps'`
- Add check to make sure the source bucket is `linz-imagery` or `nz-imagery`
- get the region from source url
=> feat(basemaps): Get the region from collection.json and validate the source and target bucket.

package-lock.json, package.json, src/commands/basemaps-github/create-pr.ts, src/commands/basemaps-github/github.ts, src/commands/basemaps-github/make.cog.github.ts
Remove this `@basemaps/shared` from argo-tasks. This is not needed here.
=> feat(basemaps): Remove the @basemaps/shared package from argo-tasks.

src/commands/basemaps-github/create-pr.ts, src/commands/basemaps-github/make.cog.github.ts
After fitting this cli into cogify map reduce way, we have to take array of inputs as target location. Now we also need to fix this take same input for the vector data update.
- Pass the array of vector target and prepare vector layer.
- Vector config layer line is shorter than 200 width of prettier config, so we break the line in JSON first before prettier to make the format consistent.
=> fix(basemaps): Fix the create pull request cli input to support the vector layer as well.

.github/pull_request_template.md
It is nice to have a bit of a description with pull request explaining why the pull request is needed
Add the standard Motivation/Modification pull request template.
=> build: add pull request template

package-lock.json, package.json, src/commands/basemaps-github/create-mapsheet.ts, src/commands/basemaps-mapsheet/__test__/create-mapsheet.test.ts, src/commands/basemaps-mapsheet/create-mapsheet.ts, src/commands/index.ts
This cli is mostly using for argo workflow not basemaps, we are move it into argo-tasks.
- Relocate the create-mapsheet cli into argo tasks
- Update it using the ts-cmd
=> feat(basemaps): Move create-mapsheet into argo task. BM-879

src/commands/basemaps-mapsheet/create-mapsheet.ts
We usually gzip basemap config file before upload into s3. If we want to ready it from s3 we need to be able to decompress it automatically.
=> feat(basemaps): Decompress basemaps config json file if it is gzip file.

.github/dependabot.yml, .github/workflows/actionlint.dockerfile, .github/workflows/push.yml, .github/workflows/release-please.yml
=> feat: Lint workflows using actionlint TDE-919

src/commands/lint/__test__/lint.test.ts
The original code just asserted that we were able to create an anonymous
function to call the function under test, and didn't actually run the
function.
=> fix: Run code under test TDE-968

package-lock.json, package.json, src/commands/common.ts, src/commands/tileindex-validate/__test__/tileindex.validate.data.ts, src/commands/tileindex-validate/__test__/tileindex.validate.test.ts, src/commands/tileindex-validate/tileindex.validate.ts, src/utils/__test__/geotiff.test.ts, src/utils/geotiff.ts
There are a couple bugs with the current version of @cogeotiff/core that are fixed in the latest version, however the latest version uses a new structure for fetching data that is not compatiable with the current version of @chunkd/fs, upgrading @chunkd/fs was going to be a lot of work so  create a simple wrapper around it to give to @cogeotiff/core
Upgrades @cogeotiff/core to the latest version.
=> fix: upgrade to latest cogeotiff to fix a number of bugs TDE-835 TDE-945

src/commands/tileindex-validate/__test__/tileindex.validate.data.ts, src/commands/tileindex-validate/__test__/tileindex.validate.test.ts, src/commands/tileindex-validate/tileindex.validate.ts, src/utils/__test__/geotiff.test.ts, src/utils/__test__/mapsheet.test.ts, src/utils/geotiff.ts, src/utils/mapsheet.ts
Simplify the code to the point where TDE-1010 becomes easier to implement.
Renames a bunch of things for clarity, and removes some dead code.
=> refactor: Simplify mapsheet calculation code TDE-1010

src/commands/common.ts, src/fs.register.ts
A slightly simpler implementation.
=> refactor: Move default value up the stack TDE-1030

CHANGELOG.md, README.md, src/commands/basemaps-mapsheet/__test__/create-mapsheet.test.ts, src/commands/basemaps-mapsheet/create-mapsheet.ts, src/commands/create-manifest/__test__/create-manifest.test.ts, src/commands/stac-catalog/stac.catalog.ts, src/commands/stac-validate/hash.worker.ts, src/commands/tileindex-validate/tileindex.validate.ts, src/utils/mapsheet.ts
Correct spelling across the code base.
Make it easier to search through the code.
=> docs: Fix spelling

src/utils/__test__/slugify.test.ts, src/utils/slugify.ts
Accept more common punctuation in place names.
- Replace apostrophes, slashes, and commas with hyphen.
- Replace ampersands with “and”.
- Collapse multiple hyphens.
=> feat: Slugify more characters TDE-1044

src/commands/tileindex-validate/__test__/tileindex.validate.test.ts, src/commands/tileindex-validate/tileindex.validate.ts, src/utils/__test__/mapsheet.test.ts, src/utils/mapsheet.ts
Mapsheets are never validated that they actually exist in the mapsheet index.
validate the mapsheets are actually valid against a known range of mapsheet codes.
=>  feat: add isKnown function to validate mapsheet code is part of the known sheet ranges

src/utils/__test__/slugify.test.ts
Strengthen test cover of `slugify`.
Verify stability of `slugify` TDE-1030
=> test: Verify stability of `slugify` TDE-1030

src/commands/stac-sync/stac.sync.ts
Have correct documentation in the code
Document the current state of the code.
=> docs: Fix function JSDoc TDE-1030

src/commands/path/path.constants.ts
Simplify code.
Remove unused constant
=> chore: Remove unused constant TDE-1030

package-lock.json, package.json
Simplify dependency tree.
Remove esno
=> build: remove esno as its not used TDE-1030

src/commands/copy/copy.ts
=> chore: Remove unused special case for JSON input TDE-1030

src/commands/stac-github-import/stac.github.import.ts
There is no Basemaps config-url link file output from the standardising workflow as this is not yet supported in Basemaps production.
Ignore the missing config-url if the repository is `linz/elevation`.
=> fix: handle missing elevation basemaps config-url TDE-1100

src/commands/stac-github-import/stac.github.import.ts
Actually use the variable value as the record key.
=> fix: Change bareword key to variable reference TDE-1100

src/commands/basemaps-github/create-pr.ts, src/commands/basemaps-github/make.cog.github.ts, src/commands/stac-github-import/stac.github.import.ts
To ensure Jira includes all relevant information about a ticket it would be good if any pull requests relating to a ticket are automatically linked into JIRA
Adds the ticket number to branches, commits and pull requests if a ticket is supplied
=> feat: add ticket numbers to the suffixes of commits and branches TDE-1146

src/commands/basemaps-github/create-pr.ts
We are populating title inside collection.json file from the etl. The `collection.title` is the combined title when processing multiple vector layers which is using the parameter from `etl --title`. And all the `collection.links` should contain the `lds:title` from the lds export. We should using this title when there is only one lds layer exists in the etl output.
Get the title from collection.json and get the title from `lds:title` for individual vector output.
=> feat(basemaps): Get vector title from the collection.json file. BM-1017

.github/workflows/push.yml, .github/workflows/release-please.yml, Dockerfile, package-lock.json, package.json
Keep our software up to date, and get any useful features, fixes, and optimisations from new versions of dependencies.
1. Update the engine:
``` jq '.engines.node = "^20.13.1"' package.json | sponge package.json ```
2. Update the lock file:
``` npm install ```
3. Update the uses of `linz/action-typescript`:
```
for path in .github/workflows/*.y*ml; do yq --inplace '(.jobs.*.steps[] | select(.uses == "linz/action-typescript*").with.node-version) = "20.x"' "$path" done
```
4. Update Dockerfile reference
=> build: update to Node.js 20 TDE-1090

.github/workflows/push.yml, .github/workflows/release-please.yml
the github action is currently broken due to a syntax error
removes " " from the startsWith as it seems to cause issues with the linter?
=> fix: build process where it doesnt like " "

src/commands/basemaps-github/__test__/create-pr-handler.test.ts
=> test: Use mock directly

src/commands/tileindex-validate/__test__/tileindex.validate.test.ts, src/commands/tileindex-validate/tileindex.validate.ts
When validation fails the errors are logged as a `Error` object, by default the logger does not seralize classes so it gets logged as `"reason": {}` which is very unhelpful to know why something failed
When failing a validation check, log out the reason as a string, the file that failed and the preset that was being checked at the time.
Added unit tests for the preset validation
=> fix(tileindex-validate): log errors when validating presets fail

README.md
Added missing space in usage example.
Fix usage example so it can be copied and pasted without modification.
=> docs: fix code example for identify-updated-items

.github/pull_request_template.md
Aligning with other of our repos.
Modify the PR template
=> build: update PR template

src/commands/basemaps-github/__test__/create-pr-handler.test.ts, src/commands/basemaps-github/create-pr.ts, src/commands/basemaps-github/make.cog.github.ts, src/commands/stac-github-import/stac.github.import.ts
We want to pass a pull request body for the basemaps-config pr with the link of ODR pull request. So that we can pass the pr link via body from argo.
- Pass the body as cmd parameter 
- Output pr link from `stac-github-import cmd`, so that we can pass that into basemaps `create-pr`
=> feat(basemaps): Pass ODR pull request url into basemap-config PR. BM-1324

src/commands/tileindex-validate/__test__/tileindex.validate.test.ts, src/commands/tileindex-validate/tileindex.validate.ts
As an imagery maintainer
I want to make sure the resolution of all TIFF images matches
so that the data is consistent and accurate (in line with the metadata)
This change is to validate all TIFFs have a consistent GSD and make the GSD available to other workflow steps.
Extract GSD (resolution) from all tiff files that get processed.
Output GSD to a file for use by argo workflows
Added tests.
Unit tests.
=> feat: tileindex-validate to output GSD TDE-1655
